version: '3.8'

services:
 postgres:
    image: postgres:14.0
    environment:
      POSTGRES_DB: 'balancer'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '127.0.0.1:5433:5432'